""" Function that prints My name is <first name> <last name> """

""" Import function """
>>> say_my_name = __import__('3-say_my_name').say_my_name

""" S U C C E S S  C A S E S """

    >>> say_my_name()
    Traceback (most recent call last):
    	      ...
    TypeError: say_my_name() missing 1 required positional argument: 'first_name'

    >>> say_my_name(1)
    Traceback (most recent call last):
    	      ...
    TypeError: first_name must be a string

    >>> say_my_name(1, 2)
    Traceback (most recent call last):
    	      ...
    TypeError: first_name must be a string

    >>> say_my_name(John, Smith)
    Traceback (most recent call last):
    	      ...
    NameError: name 'John' is not defined

    >>> say_my_name(Walter, White)
    Traceback (most recent call last):
    	      ...
    NameError: name 'Walter' is not defined

    >>> say_my_name("John", Smith)
    Traceback (most recent call last):
    	      ...
    NameError: name 'Smith' is not defined

    >>> say_my_name("Walter", White)
    Traceback (most recent call last):
    	      ...
    NameError: name 'White' is not defined

    >>> say_my_name(Walter, "White")
    Traceback (most recent call last):
    	      ...
    NameError: name 'Walter' is not defined

    >>> say_my_name(John, "Smith")
    Traceback (most recent call last):
    	      ...
    NameError: name 'John' is not defined

    >>> say_my_name(Bob)
    Traceback (most recent call last):
    	      ...
    NameError: name 'Bob' is not defined

    >>> say_my_name("Walter")
    My name is Walter 

    >>> say_my_name("John")
    My name is John 

    >>> say_my_name(2, Smith)
    Traceback (most recent call last):
    	      ...
    NameError: name 'Smith' is not defined

    >>> say_my_name(2, "Smith")
    Traceback (most recent call last):
    	      ...
    TypeError: first_name must be a string

    >>> say_my_name("John", 2)
    Traceback (most recent call last):
    	      ...
    TypeError: last_name must be a string

    >>> say_my_name("John", "Smith", "Perez")
    Traceback (most recent call last):
    	      ...
    TypeError: say_my_name() takes from 1 to 2 positional arguments but 3 were given
